[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [{ name = "Matthew Li", email = "matthew.li10@education.nsw.gov.au" }]
requires-python = ">=3.12,<4.0"
dependencies = [
    "python-dotenv (>=1.2.2,<2.0.0)",
    "quart[dotenv] (>=0.20.0,<0.21.0)",
    "aiortc (>=1.14.0,<2.0.0)",
    "quart-cors (>=0.8.0,<0.9.0)",
    "filetype (>=1.2.0,<2.0.0)",
    "pillow (>=12.1.1,<13.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pywebpush @ vendor/pywebpush",
    "hypercorn (>=0.18.0,<0.19.0)",
    "sqlalchemy[aiosqlite] (>=2.0.48,<3.0.0)",
    "quart-sqlalchemy @ vendor/quart-sqlalchemy",
    "uvloop (>=0.22.1,<0.23.0) ; sys_platform != 'win32'",
    "flask (>=3.1.3,<4.0.0)",
    "quart-rate-limiter (>=0.12.1,<0.13.0)",
    "better-profanity (>=0.7.0,<0.8.0)",
]

[tool.poetry]
packages = [{ include = "inter", from = "src" }]

[tool.pytest]
testpaths = ["tests"]

[tool.poetry.group.dev.dependencies]
pytest = "9.0.3"
hypothesis = "^6.152.7"
anyio = "4.13.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
