[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [{ name = "Matthew Li", email = "matthew.li10@education.nsw.gov.au" }]
requires-python = ">=3.12"
dependencies = [
    "python-dotenv (>=1.2.1,<2.0.0)",
    "quart[dotenv] (>=0.20.0,<0.21.0)",
    "aiortc (>=1.14.0,<2.0.0)",
    "quart-cors (>=0.8.0,<0.9.0)",
    "filetype (>=1.2.0,<2.0.0)",
    "pillow (>=12.1.0,<13.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pywebpush (>=2.2.0,<3.0.0)",
]

[tool.poetry]
packages = [{ include = "inter", from = "src" }]

[tool.pytest]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"
hypothesis = "^6.148.7"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
