CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE `sessions` (`id` TEXT PRIMARY KEY UNIQUE NOT NULL, `secret_hash` BLOB NOT NULL, `created_at` INTEGER NOT NULL, `user` INTEGER NOT NULL REFERENCES `users`(`id`)) STRICT;
CREATE TABLE IF NOT EXISTS "users" (`id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, `username` TEXT UNIQUE NOT NULL, `stream_token` TEXT NOT NULL, `password_hash` BLOB, `salt` TEXT NOT NULL, `colour` INTEGER NOT NULL, `avatar` BLOB, `display_name` TEXT NOT NULL) STRICT;
CREATE TABLE `roles` (`id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, `name` TEXT NOT NULL, `icon` BLOB NOT NULL) STRICT;
CREATE TABLE `users_roles` (`id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, `user` INTEGER NOT NULL REFERENCES `users`(`id`), `role` INTEGER NOT NULL REFERENCES `roles`(`id`)) STRICT;
