CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS `sessions` (`id` TEXT PRIMARY KEY UNIQUE NOT NULL, `secret_hash` BLOB NOT NULL, `created_at` INTEGER NOT NULL, `user` INTEGER NOT NULL REFERENCES `users`(`id`)) STRICT;
CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, `username` TEXT UNIQUE NOT NULL, `stream_token` TEXT NOT NULL, `password_hash` BLOB, `salt` TEXT NOT NULL, `colour` INTEGER NOT NULL, `avatar` BLOB, `display_name` TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS `roles` (`id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, `name` TEXT NOT NULL, `icon` BLOB NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS `users_roles` (`id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, `user` INTEGER NOT NULL REFERENCES `users`(`id`), `role` INTEGER NOT NULL REFERENCES `roles`(`id`), UNIQUE (user, role)) STRICT;
CREATE TABLE IF NOT EXISTS `follow` ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,`follower` INTEGER NOT NULL REFERENCES `users`(`id`), `followee` INTEGER NOT NULL REFERENCES `users`(`id`), UNIQUE (`follower`, `followee`)) STRICT;
