name: Build

on:
  push:
    branches:
      - "svelte-static"
  pull_request:
    branches:
      - "svelte-static"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd frontend
      - uses: actions/setup-node@v6
        with:
          node-version: 25
      - run: npm ci
      - run: npm run build
      - run: cd ..
      - uses: actions/upload-artifact@v4
        with:
          path: .
