name: Build

on:
  push:
    branches:
      - "svelte-static"
  pull_request:
    branches:
      - "svelte-static"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          cd frontend
          pnpm i --frozen-lockfile
          pnpm run build
          rm -rf node_modules
          cd ../backend
          python -m pip install poetry poetry-plugin-export
          python -m poetry export -f requirements.txt > requirements.txt
      - uses: actions/upload-artifact@v4
        with:
          path: .
          include-hidden-files: true
